name: Build, Merge, and Push

permissions:
  packages: write

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches:
      - main
env:
  REGISTRY_REPO: 'ghcr.io/${{ github.repository }}'
  TAG: 'latest'

jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4
      - name: Build and push containers
        env:
          PLATFORM: ${{ matrix.platform }}
          ARCH: ${{ matrix.platform == 'linux/amd64' && 'amd64' || 'arm64' }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
        run: |
          echo -n $password | docker login -u $username --password-stdin $registry $REGISTRY_REPO/ympd:latest
          docker push $REGISTRY_REPO/ympd:latest
