name: Build, Merge, and Push

permissions:
  packages: write

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches:
      - main
env:
  REGISTRY_REPO: 'ghcr.io/${{ github.repository }}'
  TAG: 'latest'

jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64,linux/arm64

      - name: Build and push containers
        env:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
        run: |
          echo -n $password | docker login -u $username --password-stdin $registry
          docker buildx build --push --platform=linux/arm64,linux/amd64 -t $REGISTRY_REPO/ympd:latest .
